services:
  - type: web
    name: conectar-mulheres
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /inicio
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.7
